#!/usr/bin/env bash
# Inert, source-pinned evaluation lane for MiaAI-Lab's Qwen3.8-Flash-Next
# one-DGX-Spark vLLM recipe. This script does nothing without an explicit action.
# It never modifies Hermes/Loca configuration and --start never kills a workload.
set -euo pipefail

SOURCE_REPO="https://github.com/MiaAI-Lab/Qwen3.8-Flash-Next-Single-DGX-Spark.git"
SOURCE_REV="554f295f0ac744cff8a5ffd4dd3bcc96aa82ab7f"
MODEL_REPO="Mia-AiLab/Qwen3.8-Flash-Next-NVFP4"
MODEL_REV="925d7be6c14c6c9442ef83e8f05b5a3c39304f69"
# Arm64 manifest resolved 2026-09-04; never silently follow the mutable tag.
IMAGE="vllm/vllm-openai@sha256:3b0e188ffceb3d07e09c3cb5215433a0020eacf02d7f882ed3a8bfd15454477e"
RUNTIME_DIR="${MIA_QWEN38_RUNTIME_DIR:-$HOME/src/qwen38-flash-next-mia-262k}"
MODEL_HOME="${MIA_QWEN38_MODEL_HOME:-$HOME/models/hf}"
PORT="${MIA_QWEN38_PORT:-8888}"
DO_CHECK=0
DO_STAGE=0
DO_DOWNLOAD=0
DO_START=0

usage() {
  cat <<'USAGE'
Usage: switch-to-qwen38-flash-next-mia-nvfp4-220k.sh [--check] [--stage] [--download] [--start]

No action is performed without a flag.
  --check     validate pinned artifacts and local prerequisites; does not change state
  --stage     clone the exact upstream source and write a native-262K evaluation .env
  --download  fetch only the exact pinned checkpoint revision into ~/models/hf
  --start     refuse co-residence, then delegate launch to the pinned upstream script

The staged default is deliberately conservative: native 220,000 context,
YaRN off, BF16/auto KV, MTP disabled, and two concurrent lanes. The author FP8-KV + MTP=3 profile is
recorded in the runbook as a later, separately measured experiment.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) DO_CHECK=1 ;;
    --stage) DO_STAGE=1 ;;
    --download) DO_DOWNLOAD=1 ;;
    --start) DO_START=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done
(( DO_CHECK || DO_STAGE || DO_DOWNLOAD || DO_START )) || { usage >&2; exit 2; }

require_prerequisites() {
  [[ "$(uname -m)" == "aarch64" ]] || { echo "Refusing: DGX Spark requires aarch64." >&2; return 1; }
  command -v docker >/dev/null || { echo "Refusing: docker is required." >&2; return 1; }
  command -v nvidia-smi >/dev/null || { echo "Refusing: nvidia-smi is required." >&2; return 1; }
  nvidia-smi --query-gpu=name --format=csv,noheader | grep -qx 'NVIDIA GB10' || {
    echo "Refusing: expected NVIDIA GB10." >&2; return 1;
  }
}

verify_source() {
  [[ -d "$RUNTIME_DIR/.git" ]] || { echo "Missing upstream source; run --stage." >&2; return 1; }
  [[ "$(git -C "$RUNTIME_DIR" rev-parse HEAD)" == "$SOURCE_REV" ]] || {
    echo "Source revision mismatch; refusing." >&2; return 1;
  }
  [[ -f "$RUNTIME_DIR/.oracle-220k-identity" ]] || { echo "Missing staged identity marker." >&2; return 1; }
  grep -qx "source=$SOURCE_REV" "$RUNTIME_DIR/.oracle-220k-identity"
  grep -qx "model=$MODEL_REV" "$RUNTIME_DIR/.oracle-220k-identity"
  grep -qx "image=$IMAGE" "$RUNTIME_DIR/.oracle-220k-identity"
}

verify_model() {
  local snapshot="$MODEL_HOME/hub/models--Mia-AiLab--Qwen3.8-Flash-Next-NVFP4/snapshots/$MODEL_REV"
  [[ -f "$snapshot/config.json" ]] || { echo "Missing exact model snapshot; run --download." >&2; return 1; }
  [[ -f "$snapshot/.oracle-model-revision" ]] || { echo "Missing model revision marker." >&2; return 1; }
  [[ "$(<"$snapshot/.oracle-model-revision")" == "$MODEL_REV" ]] || { echo "Model revision mismatch; refusing." >&2; return 1; }
}

stage() {
  require_prerequisites
  if [[ -d "$RUNTIME_DIR/.git" ]]; then
    git -C "$RUNTIME_DIR" fetch --depth 1 origin "$SOURCE_REV"
  elif [[ -e "$RUNTIME_DIR" ]]; then
    echo "Refusing: $RUNTIME_DIR exists but is not a git checkout." >&2; return 1
  else
    mkdir -p "$(dirname "$RUNTIME_DIR")"
    git clone "$SOURCE_REPO" "$RUNTIME_DIR"
    git -C "$RUNTIME_DIR" fetch --depth 1 origin "$SOURCE_REV"
  fi
  git -C "$RUNTIME_DIR" checkout --detach "$SOURCE_REV"
  [[ "$(git -C "$RUNTIME_DIR" rev-parse HEAD)" == "$SOURCE_REV" ]] || { echo "Pinned checkout failed." >&2; return 1; }
  cat > "$RUNTIME_DIR/.env" <<EOF
# Generated by our source-pinned 220K evaluation wrapper. Do not use for 512K/1M claims.
IMAGE="$IMAGE"
TP1_MODEL_ID="$MODEL_REPO"
# Preserve the established Qwen Flash endpoint contract across engines and
# quantizations. The deployment recipe—not the API model name—identifies
# this Mia NVFP4 evaluation variant.
SERVED_MODEL_NAME="qwen3.8-flash-next"
HF_HOME="$MODEL_HOME"
YARN=0
MAX_MODEL_LEN=220000
YARN_MAX_MODEL_LEN=524288
MTP_NUM_SPECULATIVE_TOKENS=0
KV_TARGET_GIB=20
KV_CACHE_DTYPE=auto
MAX_NUM_SEQS=2
# Force vLLM's offline hub lookup to the exact downloaded snapshot; do not
# let a mutable default branch name select a different model revision. vLLM's
# server-side defaults merge with per-request chat_template_kwargs; low is the
# service default while callers may explicitly override it when warranted.
# Keep the JSON in literal single quotes through upstream start.sh's generated
# shell launch script; otherwise shell brace expansion splits its comma.
EXTRA_VLLM_ARGS="--revision $MODEL_REV --default-chat-template-kwargs '{\"enable_thinking\":true,\"reasoning_effort\":\"low\"}'"
HOST_SLACK_GIB=5
# Verified direct-Docker GB10 path after cold boot; without privileged access
# ordinary --gpus all containers can see NVML but fail CUDA context creation.
EXTRA_DOCKER_ARGS="--privileged"
PORT=$PORT
EOF
  printf 'source=%s\nmodel=%s\nimage=%s\n' "$SOURCE_REV" "$MODEL_REV" "$IMAGE" > "$RUNTIME_DIR/.oracle-220k-identity"
  verify_source
  echo "[mia-qwen38-220k] staged source-pinned native-262K evaluation configuration."
}

download() {
  verify_source
  python3 - <<PY
from huggingface_hub import model_info, snapshot_download
repo = "$MODEL_REPO"
revision = "$MODEL_REV"
cache_dir = "$MODEL_HOME/hub"
info = model_info(repo, revision=revision)
if info.sha != revision:
    raise SystemExit(f"resolved {info.sha}, expected {revision}")
snapshot_download(repo_id=repo, revision=revision, cache_dir=cache_dir)
PY
  local model_root="$MODEL_HOME/hub/models--Mia-AiLab--Qwen3.8-Flash-Next-NVFP4"
  local snapshot="$model_root/snapshots/$MODEL_REV"
  [[ -f "$snapshot/config.json" ]] || { echo "Expected exact snapshot was not created." >&2; return 1; }
  mkdir -p "$model_root/refs"
  # The upstream server starts from a repo ID in offline mode. Map its default
  # main revision to this exact audited snapshot; it must never resolve online.
  printf '%s\n' "$MODEL_REV" > "$model_root/refs/main"
  # This vLLM image's hub client resolves its cache directly beneath HF_HOME,
  # while upstream start.sh validates beneath HF_HOME/hub. Keep one canonical
  # cache under ~/models/hf/hub and expose a compatibility symlink, not a copy.
  ln -sfn "hub/models--Mia-AiLab--Qwen3.8-Flash-Next-NVFP4" "$MODEL_HOME/models--Mia-AiLab--Qwen3.8-Flash-Next-NVFP4"
  printf '%s\n' "$MODEL_REV" > "$snapshot/.oracle-model-revision"
  verify_model
  echo "[mia-qwen38-220k] exact model revision staged under ~/models/hf."
}

occupancy() {
  local found=0 line
  echo "[mia-qwen38-220k] exclusive-occupancy scan:"
  # Docker is the authority for containerized vLLM. Do not scan arbitrary shell
  # command lines for the word “vllm”: an SSH monitor command or a stale
  # memwatcher can contain a container name and create a false busy result.
  # Native engines are identified by their actual executable names.
  while IFS= read -r line; do
    echo "  process: $line"; found=1
  done < <(ps -axo pid=,comm= | grep -Ei '[l]lama-server|[d]s4|[l]ing' || true)
  while IFS= read -r line; do echo "  container: $line"; found=1; done < <(docker ps --format '{{.ID}} {{.Names}} {{.Image}}' | grep -Ei '[v]llm|[l]lama|[d]s4|[l]ing|qwen' || true)
  (( found == 0 )) || { echo "Refusing: candidate requires exclusive Spark occupancy; nothing was stopped." >&2; return 1; }
}

start() {
  require_prerequisites
  verify_source
  verify_model
  occupancy
  echo "[mia-qwen38-220k] validating a real CUDA allocation in the exact pinned image."
  docker run --rm --privileged --gpus all --entrypoint python3 "$IMAGE" -c '
import torch
assert torch.cuda.is_available(), "CUDA unavailable"
torch.zeros(1, device="cuda").add_(1).cpu()
print("CUDA allocation OK:", torch.cuda.get_device_name(0))
'
  echo "[mia-qwen38-220k] starting source-pinned native 220K baseline on port $PORT."
  echo "[mia-qwen38-220k] this uses upstream AGPL-3.0-or-later launch code; source remains in $RUNTIME_DIR."
  (cd "$RUNTIME_DIR" && ./start.sh)
}

if (( DO_STAGE )); then stage; fi
if (( DO_CHECK )); then
  require_prerequisites
  verify_source || true
  verify_model || true
fi
if (( DO_DOWNLOAD )); then download; fi
if (( DO_START )); then start; fi
